# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3544be4596e84e3fee10dc501508a7f536660e04916608d5119bc8729a7633305ce761efefc7c16254971c326d7c5d829beb8fd360f8a45f3f624f69a8e0184

test:
  secret_key_base: 54288d1ee7bdce7a6c9f59e3e9c8450f1e114b53285104bbfcb71624d418216395f3a71be7a4a26065f2f9f4f3b985da0c2fe8087fe62dd6a56f18d0c0921f73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
